trigger:
- main

pool:
  name: 'reem'

steps:
# Create virtual environment
- powershell: |
    python -m venv ~\.udacity-devops
  displayName: 'Create virtual environment'

# Install dependencies
- powershell: |
    & ~\.udacity-devops\Scripts\Activate.ps1 -Verbose
    pip install --upgrade pip -Verbose
    pip install -r requirements.txt -Verbose
  displayName: 'Install dependencies'


# Run lint
- powershell: |
    & ~\.udacity-devops\Scripts\Activate.ps1
    pylint --disable=R,C,W1203,W0702 app.py
  displayName: 'Run lint'

# Run tests
- powershell: |
    & ~\.udacity-devops\Scripts\Activate.ps1
    python -m pytest -vv --cov=myrepolib tests/*.py
  displayName: 'Run tests'
