trigger:
- main

pool:
  name: 'reem'

steps:
- script: make setup
  displayName: 'Create virtual environment'

- script: |
    source ~/.udacity-devops/bin/activate
    make all
  displayName: 'Activate Env and Run Makefile'
