trigger:
- main

pool:
  name: reem  # your agent pool name

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- powershell: |
    python -m venv venv
    .\venv\Scripts\Activate.ps1
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- powershell: |
    .\venv\Scripts\Activate.ps1
    pylint --disable=R,C,W1203,W0702 app.py
  displayName: 'Lint'

- powershell: |
    .\venv\Scripts\Activate.ps1
    python -m pytest -vv --cov=myrepolib tests/*.py
  displayName: 'Test'
